#
#    _______                              ______
#   |__   __|                            / ____|
#      | |  ___ __      __ _ __   _   _ | |      ___   _ __  ___
#      | | / _ \\ \ /\ / /| '_ \ | | | || |     / _ \ | '__|/ _ \
#      | || (_) |\ V  V / | | | || |_| || |____| (_) || |  |  __/
#      |_| \___/  \_/\_/  |_| |_| \__, | \_____|\___/ |_|   \___|
#                                  __/ |
#                                 |___/
#
#    The most customizable Towny expansion plugin for your Towny server!
#                        Developed by Pesto

expansions:

    # Enables the miner kit where a full set of iron armor will give infinite haste, fire resistance and night vision
    enable-miner-kit: true

    # Enables blocking of modern combat sounds.
    enable-old-combat-sounds: true

    # Enable rallying (Requires Apollo)
    enable-rallies: true

    # Enable Essentials-like player messaging
    enable-messaging: true

    # Enable the Team module to show allies when entering a siege zone
    enable-team-indicator: true

    # When entering the siege zone, players will be able to see the banner using a specific indicator
    # type. The color of the indicator will use SiegeWar's beacon settings even disabled.
    #
    # Indicator types: none, waypoint, beam
    enable-banner-indicator: 'waypoint'

# Do not modify or things will break :p
config-version: 1